title: Pragmatic Lightning
description: >-
  Build a Bitcoin Lightning app from scratch.
theme: jekyll-theme-leap-day
markdown: kramdown
google_analytics: UA-139351657-1
twitter:
  username: scalefree_
social:
  name: Mitchell V
  links:
    - https://twitter.com/scalefree_
plugins:
  - jekyll-seo-tag
exclude:
  - .idea
  - rain-report/node_modules
  - rain-report/bitcoind_data
  - rain-report/lnd_data