title: Pragmatic Lightning
description: >-
  Build a Bitcoin Lightning app from scratch.
remote_theme: allejo/jekyll-docs-theme
markdown: kramdown
analytics:
  google: UA-139351657-1
project: {}
social:
  github:
    user: mvanderh
    repo: pragmatic-lightning
  twitter:
    enabled: true
    account: scalefree_
plugins:
  - jekyll-seo-tag
exclude:
  - .idea
  - rain-report/node_modules
  - rain-report/bitcoind_data
  - rain-report/lnd_data